name: Build and release on push

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Github Release
        uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/#10/')
        env:
          GHR_COMPRESS: xz
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

