name: Build and release on push

on:
  push:
#    branches:
#      - 'release/**'
#      - '!release/**-snapshot'

jobs:

  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
#      - run: npm login -u ${{OWNER}} -p ${{secrets.GITHUB_TOKEN}}
#      - run: npm publish --access=public

#  release:
#    name: Release
#    runs-on: ubuntu-latest
#    steps:
      - name: Github Release
        uses: fnkr/github-action-ghr@v1.3
#        if: startsWith(github.ref, 'refs/*/')
        env:
          GHR_COMPRESS: xz
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

