name: Upload to Github

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Bintray
          env:
            - GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            npm i
            npm run build
            npm config set @huluvu424242:registry https://npm.pkg.github.com/
            npm publish  --access=public

#      - uses: actions/setup-node@v1
#        with:
#          node-version: '14.x'
#          registry-url: 'https://npm.pkg.github.com'
#          # Defaults to the user or organization that owns the workflow file
#          scope: '@FunThomas424242'
#      - run: npm install
#      - run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
